BOARD_ADDED = 'BOARD_ADDED'

LIST_ADDED = 'LIST_ADDED'
LIST_UPDATED = 'LIST_UPDATED'
LIST_DELETED = 'LIST_DELETED'

CARD_ADDED = 'CARD_ADDED'
CARD_UPDATED = 'CARD_UPDATED'
CARD_DELETED = 'CARD_DELETED'
