"""empty message

Revision ID: 16dbf9a07dd1
Revises: fe08cd3b9a6a
Create Date: 2019-08-04 09:44:57.068949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dbf9a07dd1'
down_revision = 'fe08cd3b9a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'is_demo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('is_demo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
