"""empty message

Revision ID: 17323d05f4ec
Revises: 8595ba2267b1
Create Date: 2019-07-23 08:05:50.834384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17323d05f4ec'
down_revision = '8595ba2267b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('users', sa.String(length=255), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'users')
    # ### end Alembic commands ###
