"""empty message

Revision ID: 4ba7aac9c306
Revises: add616d7ebbc
Create Date: 2019-07-23 07:38:41.543892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba7aac9c306'
down_revision = 'add616d7ebbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('owner', sa.Integer(), nullable=True))
    op.add_column('boards', sa.Column('users', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_constraint('boards_uid_fkey', 'boards', type_='foreignkey')
    op.create_foreign_key(None, 'boards', 'users', ['owner'], ['id'])
    op.drop_column('boards', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.create_foreign_key('boards_uid_fkey', 'boards', 'users', ['uid'], ['id'])
    op.drop_column('boards', 'users')
    op.drop_column('boards', 'owner')
    # ### end Alembic commands ###
