"""empty message

Revision ID: 6a4a0199370a
Revises: 17323d05f4ec
Create Date: 2019-08-01 19:07:38.540985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4a0199370a'
down_revision = '17323d05f4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('members', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'members')
    # ### end Alembic commands ###
