"""empty message

Revision ID: 7a54ae7c3ec4
Revises: dbc99c194ca6
Create Date: 2019-08-01 19:58:09.831429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a54ae7c3ec4'
down_revision = 'dbc99c194ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_boards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_boards',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name='users_boards_board_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_boards_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'board_id', name='users_boards_pkey')
    )
    op.drop_table('board_members')
    # ### end Alembic commands ###
