"""empty message

Revision ID: c243bfabdde7
Revises: 8ca014aef600
Create Date: 2019-01-06 08:26:02.307695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c243bfabdde7'
down_revision = '8ca014aef600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('uid', sa.Integer(), nullable=True))
    op.drop_constraint('boards_user_fkey', 'boards', type_='foreignkey')
    op.create_foreign_key(None, 'boards', 'users', ['uid'], ['id'])
    op.drop_column('boards', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.create_foreign_key('boards_user_fkey', 'boards', 'users', ['user'], ['id'])
    op.drop_column('boards', 'uid')
    # ### end Alembic commands ###
