"""empty message

Revision ID: dbc99c194ca6
Revises: 6a4a0199370a
Create Date: 2019-08-01 19:28:23.138800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbc99c194ca6'
down_revision = '6a4a0199370a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_boards',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'board_id')
    )
    op.drop_column('boards', 'members')
    op.drop_column('boards', 'users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('users', sa.VARCHAR(length=255), server_default=sa.text("'[]'::character varying"), autoincrement=False, nullable=True))
    op.add_column('boards', sa.Column('members', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_table('users_boards')
    # ### end Alembic commands ###
