"""empty message

Revision ID: fe08cd3b9a6a
Revises: 7a54ae7c3ec4
Create Date: 2019-08-02 16:53:29.717725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe08cd3b9a6a'
down_revision = '7a54ae7c3ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('is_demo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'is_demo')
    # ### end Alembic commands ###
